CAMS Regional Air Quality Inventory
C2SM-RCM/emiproc pull request #69
Opened 2024-11-18 09:17 UTC by corink21

Script to read in regional air quality inventory from CAMS (v6.1-Ref2, https://eccad.sedoo.fr/#/metadata/608) on regular lat lon grid.

2024-11-18 13:40 UTC, lionel42 requested changes

2024-11-18 13:40 UTC, lionel42 commented on emiproc/grids.py
> +
Use `np.round` instead, for vectorization

2024-11-18 13:40 UTC, lionel42 commented on emiproc/inventories/cams_reg_aq.py
> +class CAMS_REG_AQ(Inventory):
Add a docstring

2024-11-18 13:40 UTC, lionel42 commented on emiproc/inventories/cams_reg_aq.py
> +            if nc_file.suffix == '.nc' and re.match(filename_pattern, nc_file.name):
Here I would move this condition above, where the nc_files list is created, so that the files selection is only done at one place

2024-11-18 13:42 UTC, lionel42 commented
@corink21  If you can change the few points I mentioned above, that would be perfect

2024-11-19 09:22 UTC, lionel42 commented
@corink21  I tried to download the the files and run the processing. Which worked well.

I have 2 more comments. 

* The temporal profiles don't originate from the website you have put right ? In this case would you agree to remove the temporal profiles part of the code and put it somewhere else in you processing script ?

* Could you check the units ? emiproc uses `kg/year/cell`

2024-11-19 09:37 UTC, corink21 commented
> * The temporal profiles don't originate from the website you have put right ? In this case would you agree to remove the temporal profiles part of the code and put it somewhere else in you processing script ?

I agree that one should move the profiles part somewhere else. I am using the TNO profiles, which don't originate from the ECCAD website. 

> * Could you check the units ? emiproc uses `kg/year/cell`

The emission dataset uses Tg/year/cell, which is then converted to kg/year/cell with UNIT_CONVERSION_FACTOR = 1.e9.

2024-11-21 07:11 UTC, lionel42 approved these changes

2024-11-21 07:12 UTC, merged